*CU Boulder GEOL 3600, Oct 2025*

# More on data analysis with the Pandas package

#### Today's notebook and data files:

Download these from canvas (under the Data Analysis with Pandas module) and upload to the explore hub:

**`12b_more_data_analysis_pandas.ipynb`**

**`alluvial_river_bankfull_geometry.csv`**

**`antarctica2015co2composite-noaa.txt`**

**`co2_annmean_mlo_1959_2024.txt`**

**`hardangerjokulen2006-2007.csv`**

**`USGS09058000_discharge_NoHead_20112021.csv`**

#### Today's topics

1. Python package presentation
2. Demystifying loops
3. Introduction to code paper #3
4. More on the Pandas data-management package

## Review from last week

### Ways to run Python code

1. In an interactive Python console (line-by-line)
2. By running code in a `.py` file (e.g., `python mycode.py`)
3. In a code cell in a Jupyter notebook

### Importing pandas

`import pandas as pd`

### Pandas `DataFrame`

Pandas defines a new variable type called a `DataFrame`. A `DataFrame` has some features in common with dictionaries, and some in common with 2D numpy arrays:

- A `DataFrame` contains tabular data in rows and columns
- Each column is identified by a header string
- Columns can be accessed with dictionary-like syntax, using the header string as the key
- Columns can have different data types
- You can add columns the same way you add items to a dictionary
- The Pandas `read_csv()` function reads a CSV file directly into a `DataFrame`
- Pandas data can be plotted using matplotlib functions, or through its own `plot()` function

In [2]:
import pandas as pd

## More on Pandas

### Wrangling text files

Unfortunately there is no universal standard for the layout and format of text-based data files. The following illustrates a few of the issues that can crops up, and tips on how to handle them.

#### Example 1: an easy case

The file `alluvial_river_bankfull_geometry.csv` is an easy one when it comes to reading. There is one header line, containing the names of the various columns. The rest of the lines represent the actual data. We can read this in one line with no fancy parameters needed:

```
ardf = pd.read_csv("alluvial_river_bankfull_geometry.csv")
ardf
```

We'll get back to this particular dataset momentarily. First, though, a slightly more complicated example.

In [3]:
ardf = pd.read_csv("alluvial_river_bankfull_geometry.csv")

In [4]:
ardf

,ID,Citation,Site_Name,Drainage area (km^2),tau_*bf,Slope,D50 (m),Width (m),Depth (m),Discharge (m3/s)
0,1,"Agouridis et al., 2011 and Brockman, 2010",Banklick Creek at Hwy 1829,77.70,0.0372,0.00510,0.0831,12.1,1.00,21.2
1,2,"Agouridis et al., 2011 and Brockman, 2010",Cave Creek near Fort Springs,6.55,0.0466,0.00740,0.0385,5.3,0.40,1.8
2,3,"Agouridis et al., 2011 and Brockman, 2010",Cedar Creek at Hwy 1442,31.34,0.0445,0.00500,0.0477,12.6,0.70,9.7
3,4,"Agouridis et al., 2011 and Brockman, 2010",Chenoweth Run at Ruckriegel Pky.,14.17,0.0357,0.00530,0.0450,13.6,0.50,4.7
4,5,"Agouridis et al., 2011 and Brockman, 2010",Cruises Creek at Hwy 17,46.62,0.0513,0.00560,0.0595,12.7,0.90,10.6
...,...,...,...,...,...,...,...,...,...,...
1651,1652,"Wolman, 1955",East Branch Brandywine Creek at Cornog,NaN,0.0200,0.00370,0.0830,17.0,0.74,24.0
1652,1653,"Wolman, 1955",East Branch Brandywine Creek at Seven Springs,NaN,0.0342,0.00280,0.0640,20.0,1.29,40.0
1653,1654,"Wolman, 1955",East Branch Brandywine Creek at South Downington,NaN,0.0049,0.00066,0.1040,18.0,1.27,45.0
1654,1655,"Wolman, 1955",West Branch Brandywine Creek at Embreeville,NaN,0.0304,0.00069,0.0220,27.0,1.60,66.0
1655,1656,"Wolman, 1955",West Branch Brandywine Creek at Wanaset,NaN,0.0115,0.00062,0.0490,23.0,1.50,68.0

#### Example 2: a csv file with *two* header lines

We've previously worked with the file `hardangerjokulen2006-2007.csv`, which contains data on summer and winter melt/accumulation of ice on a glacier in Norway, organized by altitude ranges. This file is in **csv** format, which we can handle with Pandas' `read_csv()` function. However, it has *two* header lines.

In [5]:
!cat hardangerjokulen2006-2007.csv

﻿Altitude min,Altitude max,Area,Specific winter,Specific summer
(masl),(masl),(km2),balance (m w.e.),balance (m w.e.)
1850,1865,0.09,2.7,-1.45
1800,1850,3.93,3.45,-1.5
1750,1800,4.03,3.6,-1.6
1700,1750,3.46,3.5,-1.75
1650,1700,1.94,3.2,-1.9
1600,1650,0.75,2.7,-2.1
1550,1600,0.59,2.35,-2.3
1500,1550,0.57,1.95,-2.5
1450,1500,0.29,1.73,-2.7
1400,1450,0.19,1.56,-2.95
1350,1400,0.1,1.39,-3.2
1300,1350,0.1,1.22,-3.45
1250,1300,0.27,1.05,-3.7
1200,1250,0.36,0.8,-3.95
1150,1200,0.28,0.55,-4.25
1100,1150,0.11,0.3,-4.55
1020,1100,0.05,-0.05,-4.9

In [6]:
import pandas as pd

hardf = pd.read_csv("hardangerjokulen2006-2007.csv")
hardf

   Altitude min Altitude max   Area   Specific winter  Specific summer
0        (masl)       (masl)  (km2)  balance (m w.e.)  balance (m w.e.)
1          1850         1865   0.09               2.7             -1.45
2          1800         1850   3.93              3.45              -1.5
3          1750         1800   4.03               3.6              -1.6
4          1700         1750   3.46               3.5             -1.75
5          1650         1700   1.94               3.2              -1.9
6          1600         1650   0.75               2.7              -2.1
7          1550         1600   0.59              2.35              -2.3
8          1500         1550   0.57              1.95              -2.5
9          1450         1500   0.29              1.73              -2.7
10         1400         1450   0.19              1.56             -2.95
11         1350         1400    0.1              1.39              -3.2
12         1300         1350    0.1              1.22             -3.45
13         1250         1300   0.27              1.05              -3.7
14         1200         1250   0.36               0.8             -3.95
15         1150         1200   0.28              0.55             -4.25
16         1100         1150   0.11               0.3             -4.55
17         1020         1100   0.05             -0.05              -4.9

Because the first row of each column looks like a string, the DataFrame has made all columns strings. How can we get this to be a DataFrame *without* the second header line appearing as data, and with the columns being numbers (`float` data) instead of strings?

We don't really need to keep the info in the second header line, so we can delete that row from the DataFrame. The DataFrame `drop()` method can be used to delete a row or column:

```
hardf = hardf.drop(0)
hardf
```

(Quiz: why do we have to use the assignment operation?)

In [7]:
hardf = hardf.drop(0)
hardf

   Altitude min Altitude max  Area Specific winter Specific summer
1          1850         1865  0.09             2.7            -1.45
2          1800         1850  3.93            3.45             -1.5
3          1750         1800  4.03             3.6             -1.6
4          1700         1750  3.46             3.5            -1.75
5          1650         1700  1.94             3.2             -1.9
6          1600         1650  0.75             2.7             -2.1
7          1550         1600  0.59            2.35             -2.3
8          1500         1550  0.57            1.95             -2.5
9          1450         1500  0.29            1.73             -2.7
10         1400         1450  0.19            1.56            -2.95
11         1350         1400   0.1            1.39             -3.2
12         1300         1350   0.1            1.22            -3.45
13         1250         1300  0.27            1.05             -3.7
14         1200         1250  0.36             0.8            -3.95
15         1150         1200  0.28            0.55            -4.25
16         1100         1150  0.11             0.3            -4.55
17         1020         1100  0.05           -0.05             -4.9

Great! Now all the data in our columns are numbers. But they're still represented as strings, which isn't too convenient. For example, if we tried to calculate the altitude difference by subtracting the max and min altitudes, we'd have issues...

```
hardf["Altitude max"] - hardf["Altitude min"]
```

would produce the error:
```
TypeError: unsupported operand type(s) for -: 'str' and 'str'
```
because Python doesn't have a rule for the `-` operator when the operands are strings (try it!).

pandas.core.series.Series

In [8]:
hardf["Altitude mid"] = 0.5 * (hardf["Altitude min"] + hardf["Altitude max"])

TypeError: can't multiply sequence by non-int of type 'float'

Fortunately, there's a DataFrame method called `astype()` that, by default, converts the data to a given type:

```
hardf = hardf.astype(float)
print(hardf.dtypes)
hardf["Altitude difference"] = hardf["Altitude max"] - hardf["Altitude min"]
hardf
```

That will cast all the rows and columns into `float64`. Now we can treat the columns as numpy arrays to do further analysis.

In [12]:
hardf = hardf.astype(float)
print(hardf.dtypes)

Altitude min        float64
Altitude max        float64
Area                float64
Specific winter     float64
Specific summer     float64
dtype: object

In [13]:
hardf["Altitude mid"] = 0.5 * (hardf["Altitude min"] + hardf["Altitude max"])

In [14]:
hardf

,Altitude min,Altitude max,Area,Specific winter,Specific summer,Altitude mid
1,1850.0,1865.0,0.09,2.70,-1.45,1857.5
2,1800.0,1850.0,3.93,3.45,-1.50,1825.0
3,1750.0,1800.0,4.03,3.60,-1.60,1775.0
4,1700.0,1750.0,3.46,3.50,-1.75,1725.0
5,1650.0,1700.0,1.94,3.20,-1.90,1675.0
6,1600.0,1650.0,0.75,2.70,-2.10,1625.0
7,1550.0,1600.0,0.59,2.35,-2.30,1575.0
8,1500.0,1550.0,0.57,1.95,-2.50,1525.0
9,1450.0,1500.0,0.29,1.73,-2.70,1475.0
10,1400.0,1450.0,0.19,1.56,-2.95,1425.0
11,1350.0,1400.0,0.10,1.39,-3.20,1375.0
12,1300.0,1350.0,0.10,1.22,-3.45,1325.0
13,1250.0,1300.0,0.27,1.05,-3.70,1275.0
14,1200.0,1250.0,0.36,0.80,-3.95,1225.0
15,1150.0,1200.0,0.28,0.55,-4.25,1175.0
16,1100.0,1150.0,0.11,0.30,-4.55,1125.0
17,1020.0,1100.0,0.05,-0.05,-4.90,1060.0

#### Example 3: a tab-delimited file with a long header

We've already played a bit with the Antarctic composite CO2 dataset. Now let's take a closer look at the file. Here's an excerpt:
```
# Antarctic Ice Cores Revised 800KYr CO2 Data
#----------------------------------------------------
#                World Data Service for Paleoclimatology, Boulder
#                                  and
```
(...skipping a bunch of lines here...)
```
# Data line format - tab-delimited text, variable short name as header
# Missing_Values:
age_gas_calBP	co2_ppm	co2_1s_ppm
-51.03	368.02	0.06
-48.00	361.78	0.37
```
This is a *tab-delimited text file*, with a few dozen header lines before the data section begins. All of the header lines are preceded with a `#` character. The first line without a `#` represent the names of the three quantities: `age_gas_calBP` (age of the sample in years before 1950), `co2_ppm` (CO2 concentration in parts per million), and `co2_1s_ppm` (measurement standard deviation ["one sigma" means one standard deviation from the average] in ppm).

To read this into a DataFrame using `read_csv()`, we have to make use of some of that function's optional parameters. Fortunately, there are a lot of these that we can take advantage of! In this case, we need to tell `read_csv()` to ignore lines starting with `#`. For that, we can use the `comment` parameter.

We also need to tell `read_csv()` that this is a *tab*-delimited file, not a *comma*-delimited file. For that, we can use the optional `delimiter` parameter. A tab stop is a non-printing character, but we can use the code `\t` to represent a tab. Here goes:
```
icecoredf = pd.read_csv(
    "antarctica2015co2composite-noaa.txt",
    comment="#",
    delimiter="\t"
)
icecoredf
```

In practice, reading data from a text file into Pandas often takes some monkeying around, and some careful reading of the documentation! If all else fails, you can manually edit the data file to get it into a format that `read_csv()` will handle---but if possible, it's best to leave the data file alone and instead work with the various optional arguments that `read_csv()` provides.

#### Example 4: multiple-space delimited file

The Mauna Loa CO2 data file, called `co2_annmean_mlo_1959_2024.txt`, has column values separated by two or more spaces. We can still read it with `read_csv()` but we have to get into the weeds. Specifically, we need to specify:

1. That "#" means a comment line: `comment="#"`
2. That columns are separated by two or more spaces:
       `sep='[ ]{2,}', engine='python'`
3. The names for the columns (which are hidden behind "#")

After much noodling around, here's one method I found:

In [ ]:
mldf = pd.read_csv(
    "co2_annmean_mlo_1959_2024.txt",
    sep='[ ]{2,}',    # this is regexp-speak for "2 or more spaces"
    engine='python',  # not sure why needed...
    comment="#",      # ignore comment lines starting with #
    names=["year", "co2", "uncertainty"]  # give names to columns
)

mldf

Lesson: sometimes it takes some study and trial-and-error to get your data in!

### Analyzing

Once we have data input, we usually want to analyze it in some fashion. Here are some exercises to try:

#### <span style="color:green;">EXERCISES</span>

1. Add a column to the `hardf` DataFrame that contains the mid-point altitude (average of max and min)

2. Add a column that sums the winter and summer balances to get the annual net balance.

(Note: the title of the column `"Specific summer "` has an annoying extra space at the end - you can deal with it this way, or use the `columns` attribute to edit the name...)

### Plotting data from one or more DataFrames

Once you have data in a DataFrame(s), when it comes to plotting you can treat its columns as if they were lists or NumPy arrays. The difference is that columns in a DataFrame are accessed using dictionary-like syntax. Here's an example:
```
import matplotlib.pyplot as plt

plt.plot(icecoredf["age_gas_calBP"], icecoredf["co2_ppm"], 'r')
plt.xlabel("Years before 1950")
plt.ylabel("CO2 concentration (ppm)")
plt.title("CO2 data from Antarctic ice cores")
```

#### <span style="color:green;">EXERCISES</span>

1. Using the alluvial river dataset, make a scatterplot of channel width (`Width (m)`) against discharge (`Discharge (m3/s)`)

(Remember you can get a scatterplot either with matplotlib's `plot()` function by giving something like `'.'` for its optional symbol argument, or by using matplotlib's `scatter()` function.)

2. Using the Hardangerjokul dataset, make a line plot with mid-point altitude on the y-axis, and three curves on the x-axis: the specific winter balance (in blue), the specific summer balance (in red), and the net balance (in black).

(BONUS QUESTION for those who know a bit about glaciers: can you identify the Equilibrium Line Altitude?)

3. Using the ice-core CO2 and Mauna Loa CO2 datasets, make a plot that shows both CO2 records (in different colors) as a function of time relative to the year 1950 (sound familiar??).

### Saving plots to file

To save a figure to a file, you can use the matplotlib `savefig()` function. Give it a name for the file. The filename extension indicates the format to use. Here's a little example that generates a pdf file:

```
plt.plot(mldf["year"], mldf["co2"])
plt.xlabel("Year")
plt.ylabel("CO2 concentration (ppm)")
plt.savefig("keeling_curve.pdf")
```

## Handling Date and Time stamps

Different programming languages and software packages handle date and time stamps in their own unique ways. Pandas has a set of functions for creating and managing timeseries.

We need to convert the USGS entries in the DateTime column into a format that Pandas can work with. Luckily, the to_datetime function in the Pandas library can convert it directly. Note that this conversion takes up a bit of time, wait till you see those first five lines reported....

In [ ]:
# catch up to where we were with this dataset in the last class...
data = pd.read_csv("USGS09058000_discharge_NoHead_20112021.csv")
data.columns = ['Agency', 'SiteNo', 'DateTime', 'Discharge_cfs']
data['Discharge_m3sec'] = data['Discharge_cfs'] * 0.028316847 
data

In [ ]:
# using the pd.to_datetime functionality
data['NewDateTime'] = pd.to_datetime(data['DateTime'])
data.head()

In [ ]:
#The entries in our DataFrame data are indexed by the number in bold on the left side of each row. 
# We can display a slice of the data using index ranges:

data[0:5]

## Creating data subsets and removing columns

We can select specific ranges of our data in both the row and column directions using either label or integer-based indexing.

loc: indexing via labels or integers <br>
iloc: indexing via integers <br>

To select a subset of rows AND columns from our DataFrame, we can use the loc method and the integer indices for both rows and columns.

In [ ]:
data.loc[0:2, ['DateTime', 'Discharge_m3sec']]

In [ ]:
data.iloc[0:2, -2:]

In [ ]:
print('With iloc:', data.iloc[0:2, -2:].shape)
print('With loc:', data.loc[0:2, ['DateTime', 'Discharge_m3sec']].shape)

Since we can call individual columns (or lists of columns) from a DataFrame, the simplest way to remove columns is by creating a new DataFrame with only the columns we want.

In [ ]:
discharge_data = data[['DateTime', 'Discharge_m3sec']]
discharge_data

## Using Logical Operators with DataFrames to Filter Values

Another useful data wrangling option is the ability to filter data from an existing pandas dataframe.

Filtering data is easily done using dataframe.column_name == "value". Your output will contain all rows that meet the criteria.

For example, you can filter using a comparison operator on numeric values. For example, you can select all rows from the dataframe that have discharge greater than 8500 cfs by filtering on the Discharge_in_cfs column.

In [ ]:
# create new dataframe from filter on values in the `Discharge_cfs` column greater than 8500 cfs
high_discharge_days = data[data.Discharge_cfs > 8500]

# print new dataframe
high_discharge_days